# Generated by Django 5.1.2 on 2024-12-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
