# Generated by Django 5.1.2 on 2024-12-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_oprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='oprice',
        ),
    ]
