# Generated by Django 5.1.2 on 2024-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_des',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
