# Generated by Django 5.1.2 on 2024-11-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_small_des_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='small_des',
            new_name='smalldes',
        ),
    ]
