# Generated by Django 5.1.2 on 2024-11-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_small_des_product_smalldes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='smalldes',
            new_name='smalldescrption',
        ),
    ]
