# Generated by Django 5.1.2 on 2024-11-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_smalldes_product_smalldescrption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='smalldescrption',
            new_name='smalldescription',
        ),
    ]
